=== GiulianaDaq/GameGuide/dtd/template.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT template (tappe,idstile)>
<!ATTLIST template
  xmlns CDATA #FIXED ''
  name CDATA #REQUIRED>

<!ELEMENT tappe (idtappa)+>
<!ATTLIST tappe
  xmlns CDATA #FIXED ''>

<!ELEMENT idstile (#PCDATA)>
<!ATTLIST idstile
  xmlns CDATA #FIXED ''>

<!ELEMENT idtappa ((descrizione|id)+,iddomanda)>
<!ATTLIST idtappa
  xmlns CDATA #FIXED ''
  tipo NMTOKEN #REQUIRED>

<!ELEMENT descrizione (#PCDATA)>
<!ATTLIST descrizione
  xmlns CDATA #FIXED ''>

<!ELEMENT id (#PCDATA)>
<!ATTLIST id
  xmlns CDATA #FIXED ''>

<!ELEMENT iddomanda (#PCDATA)>
<!ATTLIST iddomanda
  xmlns CDATA #FIXED ''>

=== GiulianaDaq/GameGuide/dtd/template.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE template SYSTEM "template.dtd">
<template name="Game Guide">
    <tappe>
<!--cattedrale-->
       <idtappa tipo="chiesa">
             <id>1</id>
             <descrizione></descrizione>
             <iddomanda>1</iddomanda>
       </idtappa>


<!--storia san nicola-->
       <idtappa tipo="altro">
             <id>2</id>
             <descrizione>...</descrizione>
             <iddomanda></iddomanda>
       </idtappa>

<!--basilica-->
      <idtappa tipo="chiesa">
          <descrizione></descrizione>
          <id>3</id>
          <iddomanda>7</iddomanda>
       </idtappa>

    
     </tappe>
<idstile>1</idstile>
</template>
